/** დემო მონაცემები — პირველ გაშვებაზე თუ ბაზა ცარიელია */
export const EV_CHARGING_DEMO_SEED = {
  partners: [
    {
      partnerId: 'martev-charging',
      name: 'Martev Charging',
      isActive: true,
      sortOrder: 0,
    },
    {
      partnerId: 'greenbolt-ge',
      name: 'GreenBolt საქართველო',
      isActive: true,
      sortOrder: 1,
    },
    {
      partnerId: 'voltline',
      name: 'VoltLine',
      isActive: true,
      sortOrder: 2,
    },
  ],
  stations: [
    {
      stationId: 'demo-martev-vake',
      partnerId: 'martev-charging',
      partnerName: 'Martev Charging',
      siteName: 'ვაკე — სწრაფი DC',
      address: 'ჭაბუა ამირეჯიბის გამზირი, თბილისი',
      latitude: 41.7076,
      longitude: 44.7686,
      phone: '+995 32 2 00 00 01',
      perkHint: 'პრემიუმზე −15% ჩართვაზე',
      heroImageUrl:
        'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&q=80&auto=format&fit=crop',
      rating: 4.8,
      reviewsCount: 126,
      priceLabel: '~0.48 ₾/kWh',
      chargeSpeedHint: '~35 კმ / 15 წთ',
      aboutText:
        'სწრაფი DC და AC დამტენები, კოფე ზონა და 24/7 წვდომა. Marte Premium-ით სპეციალური ფასები და პაკეტები.',
      isActive: true,
      chargers: [
        {
          id: 'c1',
          label: 'DC #1',
          connectorType: 'CCS2',
          maxPowerKw: 150,
          status: 'available',
        },
        {
          id: 'c2',
          label: 'DC #2',
          connectorType: 'CCS2',
          maxPowerKw: 150,
          status: 'occupied',
        },
        {
          id: 'c3',
          label: 'AC ზონა',
          connectorType: 'Type2',
          maxPowerKw: 22,
          status: 'available',
        },
      ],
    },
    {
      stationId: 'demo-greenbolt-saburtalo',
      partnerId: 'greenbolt-ge',
      partnerName: 'GreenBolt საქართველო',
      siteName: 'საბურთალო — მოლის პარკინგი',
      address: 'ვაჟა-ფშაველას გამზირი, თბილისი',
      latitude: 41.7254,
      longitude: 44.7698,
      phone: '+995 32 2 00 00 02',
      perkHint: 'პაკეტ „EV ყოველდღიური"',
      heroImageUrl:
        'https://images.unsplash.com/photo-1647166545674-ce28ce93bd59?w=900&q=80&auto=format&fit=crop',
      rating: 4.6,
      reviewsCount: 89,
      priceLabel: 'პაკეტით ფიქსი',
      chargeSpeedHint: '~18 კმ / 25 წთ',
      aboutText:
        'მოლის პარკინგზე — კომპაქტური DC და ორმაგი AC. იდეალურია დღის შოპინგისას დასამუხტებლად.',
      isActive: true,
      chargers: [
        {
          id: 'c1',
          label: 'DC',
          connectorType: 'CCS2',
          maxPowerKw: 60,
          status: 'available',
        },
        {
          id: 'c2',
          label: 'AC A',
          connectorType: 'Type2',
          maxPowerKw: 11,
          status: 'unknown',
        },
        {
          id: 'c3',
          label: 'AC B',
          connectorType: 'Type2',
          maxPowerKw: 11,
          status: 'available',
        },
      ],
    },
    {
      stationId: 'demo-voltline-didube',
      partnerId: 'voltline',
      partnerName: 'VoltLine',
      siteName: 'დიდუბე — სერვისცენტრი',
      address: 'დიდუბის ჩრდილოეთი, თბილისი',
      latitude: 41.7512,
      longitude: 44.7931,
      perkHint: 'პირველი ჩართვა უფასო (პრომო)',
      heroImageUrl:
        'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=900&q=80&auto=format&fit=crop',
      rating: 4.5,
      reviewsCount: 54,
      priceLabel: '~0.52 ₾/kWh',
      chargeSpeedHint: '~22 კმ / 30 წთ',
      aboutText:
        'სერვისცენტრთან ერთად — CHAdeMO და CCS. საშუალო სიმძლავრე საკმარისია უმეტეს ევროპული EV-სთვის.',
      isActive: true,
      chargers: [
        {
          id: 'c1',
          label: 'CHAdeMO',
          connectorType: 'CHAdeMO',
          maxPowerKw: 50,
          status: 'available',
        },
        {
          id: 'c2',
          label: 'CCS',
          connectorType: 'CCS2',
          maxPowerKw: 50,
          status: 'available',
        },
      ],
    },
    {
      stationId: 'demo-airport-hub',
      partnerId: 'martev-charging',
      partnerName: 'Martev Charging',
      siteName: 'შოთა რუსთაველის აეროპორტი',
      address: 'თბილისის საერთაშორისო აეროპორტი',
      latitude: 41.6697,
      longitude: 44.9574,
      phone: '+995 32 2 00 00 01',
      heroImageUrl:
        'https://images.unsplash.com/photo-1563720223185-11003d35a0a1?w=900&q=80&auto=format&fit=crop',
      rating: 4.9,
      reviewsCount: 210,
      priceLabel: '~0.55 ₾/kWh',
      chargeSpeedHint: '~55 კმ / 12 წთ',
      aboutText:
        'აეროპორტის ჰაბი — უმაღლესი სიმძლავრის DC და AC რიგი მგზავრებისთვის. ყოველთვის ღია ფრენების განრიგის მიხედვით.',
      isActive: true,
      chargers: [
        {
          id: 'c1',
          label: 'DC ჰაბი',
          connectorType: 'CCS2',
          maxPowerKw: 175,
          status: 'occupied',
        },
        {
          id: 'c2',
          label: 'AC რიგი',
          connectorType: 'Type2',
          maxPowerKw: 22,
          status: 'available',
        },
      ],
    },
  ],
};
